// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE2IlL1LCW77auJKQhJcvPJSAmmpPqlnM',
    appId: '1:1044058751162:web:1fc341749b560f0b7b8283',
    messagingSenderId: '1044058751162',
    projectId: 'mobilebasebd',
    authDomain: 'mobilebasebd.firebaseapp.com',
    storageBucket: 'mobilebasebd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrBAD0iDa0UTbdJi-BZcTNSrrNaXsxOJE',
    appId: '1:1044058751162:android:3229cd45a76fd6d67b8283',
    messagingSenderId: '1044058751162',
    projectId: 'mobilebasebd',
    storageBucket: 'mobilebasebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UNYjC-p_liOkfYd_RQuFHrHQigDVq8A',
    appId: '1:1044058751162:ios:bc56b81e12542f2e7b8283',
    messagingSenderId: '1044058751162',
    projectId: 'mobilebasebd',
    storageBucket: 'mobilebasebd.appspot.com',
    iosBundleId: 'com.example.flutterFireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UNYjC-p_liOkfYd_RQuFHrHQigDVq8A',
    appId: '1:1044058751162:ios:bc56b81e12542f2e7b8283',
    messagingSenderId: '1044058751162',
    projectId: 'mobilebasebd',
    storageBucket: 'mobilebasebd.appspot.com',
    iosBundleId: 'com.example.flutterFireBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE2IlL1LCW77auJKQhJcvPJSAmmpPqlnM',
    appId: '1:1044058751162:web:4b56557dabbc951d7b8283',
    messagingSenderId: '1044058751162',
    projectId: 'mobilebasebd',
    authDomain: 'mobilebasebd.firebaseapp.com',
    storageBucket: 'mobilebasebd.appspot.com',
  );
}
